# Approximates Prezto sorin theme

format = """$username$hostname$python$directory$character"""
right_format = """$cmd_duration$git_branch$git_status"""

[character]
success_symbol = "[❯](fg:#a6da95)[❯](fg:#eed49f)[❯](fg:#8aadf4)"
error_symbol = "[❯](fg:#ed8796)[❯](fg:#eed49f)[❯](fg:#8aadf4)"
vimcmd_symbol = "[❮](fg:#8aadf4)[❮](fg:#eed49f)[❮](fg:#ed8796)"

[directory]
truncation_length = 0
truncate_to_repo = false
style = "fg:#8aadf4"

[username]
show_always = true
format = "[$user]($style)[@](white)"
style_user = "fg:#ed8796"

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "fg:#eed49f"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = " "
style = "fg:#a6da95"

[git_status]
format = '([:](white)[$all_status$ahead_behind]($style))'
ahead = "[⬆](fg:#c6a0f6)"
behind = "[⬇](fg:#c6a0f6)"
diverged = "[⬆⬇](fg:#c6a0f6)"
modified = "[✱](fg:#8aadf4)"
staged = "[✚](fg:#a6da95)"
deleted = "[✖](fg:#ed8796)"
renamed = "[➜](fg:#c6a0f6)"
untracked = "[◼](fg:#6e738d)"
stashed = "[✭](fg:#8bd5ca)"

[python]
format = '[(\($virtualenv\) )]($style)'
style = "yellow"

[cmd_duration]
min_time = 5_000
format = "[$duration]($style) "
