#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# add Homebrew shell completions (must come before sourcing Prezto)
FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# allow bash-style shell completions
autoload -U +X bashcompinit && bashcompinit

EDITOR=vim
VISUAL=vim

# use bat for man pages
export MANPAGER="sh -c 'col -bx | bat -l man -p --theme=Smyck'"
alias cat=bat

# use Volta for managing node (required for coc)
export VOLTA_HOME="$HOME/.volta"
export PATH="$VOLTA_HOME/bin:$PATH"

# use pyenv for managing Python
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# allow pipx-installed CLIs to run
export PATH="$HOME/.local/bin:$PATH"

# required for 256 color tmux terminal
export TERMINFO_DIRS="$HOME/.local/share/terminfo/"

# configure fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# configure zoxide
eval "$(zoxide init zsh)"

# use exa instead of ls
alias ls='exa --git'
alias la='ll -a'

# jq aliases
alias jqf='jq -r | fzf --tac'
alias jql='jq -C | bat'
alias jqr='jqfzf'

# quick config file edits
alias te='vim ~/.tmux.conf.local'
alias ve='vim ~/.vim/vimrc'
alias ze='vim ~/.zshrc'

# shortcut for making python virtualenvs
mkenv() {
  python -m venv $1 && source $1/bin/activate
}

lsenv() {
  ls -a | grep -E "\.\w+env$" --color=never
}

srcenv() {
  source $1/bin/activate
}

alias toast='z node-automation && source .virtualenv/bin/activate'

# allow opening of golinks (go/<foobar>) in browser
open() {
  if [[ $1 == go/* ]]; then
    /usr/bin/open "https://$*"
  else
    /usr/bin/open $*
  fi
}

# Git aliases that don't exist in Prezto module
alias ga='git add'
alias gap='git add -p'
alias gb='git branch'
alias gba='git branch -a'
alias gc='git commit'
alias gcm='git commit -m'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gd='git diff'
alias gdc='git diff --cached'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gl='git log'
alias glp='git log -p'
alias gr='git rebase'
alias gri='git rebase -i'
alias grim='git rebase -i origin/main'
alias gro='git fetch origin && git rebase origin'
alias grom='git fetch origin && git rebase origin/main'
alias grm='git rm'
alias gs='git status'

# macOS VPN utilities
alias vpnls='scutil --nc list'
alias vpnst='scutil --nc status'
alias vpnon='networksetup -connectpppoeservice'
alias vpnoff='networksetup -disconnectpppoeservice'

# autocompletions
complete -C eero-api eero-api
eval "$(register-python-argcomplete pipx)"

zstyle -d ':completion:*' format
zstyle ':completion:*:descriptions' format '[%d]'
